Fix GitHub test_and_build failure
Failing with the following error:
```
error: failed to load manifest for workspace member `/home/runner/work/partiql-lang-rust/partiql-lang-rust/partiql-ast`
Error: failed to load manifest for workspace member `/home/runner/work/partiql-lang-rust/partiql-lang-rust/partiql-ast`
Caused by:
  failed to parse manifest at `/home/runner/work/partiql-lang-rust/partiql-lang-rust/partiql-ast/Cargo.toml`

Caused by:
  feature `edition2021` is required

  consider adding `cargo-features = ["edition2021"]` to the manifest
Error: The process '/home/runner/.cargo/bin/cargo' failed with exit code 101
```