Upgrade toolchain for GitHub coverage.yaml (#54)
We're getting some odd errors in GitHub action when building
our dependencies, upgrading the toolchain to resolve such errors.

```
error: failed to parse manifest at `/home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/ion-c-sys-macros-0.1.1/Cargo.toml`
Error: failed to parse manifest at `/home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/ion-c-sys-macros-0.1.1/Cargo.toml`
Caused by:
  feature `edition2021` is required

  consider adding `cargo-features = ["edition2021"]` to the manifest
Error: The process '/home/runner/.cargo/bin/cargo' failed with exit code 101
```